services:
  - type: web
    name: fdx-assistant
    env: python
    plan: free  # change to "starter" if you want to avoid auto-sleep
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
       sync: false
    disk:
      name: cache-disk
      mountPath: /var/cache/fdx
      sizeGB: 1
